#!/usr/bin/env bash
# build.sh - bundle src/lib/*.sh + one src/entry/NAME.sh into a single deployable dist/NAME.sh.
#
#   ./build.sh              build every entry, plus dist/gm-lib.sh (libraries only, for tests)
#   ./build.sh demo         build one entry
#   ./build.sh --check      syntax-check sources and bundles (and run shellcheck when installed)
#
# An entry that contains the line  "# build: app"  also gets src/app/*.sh (the real tool's modules),
# placed after the foundation libraries. The demo entry does not.
#
# The bundle named gemini-menu is also copied to ./gemini-menu.sh: that root file is the canonical
# install URL, so it must never drift from dist/.
#
# The bundle is one plain file: it works as  bash dist/NAME.sh,  as  curl -fsSL URL | bash,  and
# installed under /usr/local/bin. Order is the numeric prefix of the library files.
set -euo pipefail
cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

libs=(src/lib/[0-9]*.sh)
apps=(src/app/[0-9]*.sh)
# deterministic build id: a hash of the sources, so identical sources give an identical bundle (no git state, no dates)
rev=src-$(cat "${libs[@]}" "${apps[@]}" src/entry/*.sh | sha256sum | cut -c1-10)

bundle() {  # bundle OUTFILE [ENTRYFILE]
  local out=$1 entry=${2:-} f
  local -a parts=("${libs[@]}")
  if [[ -n $entry ]] && grep -q '^# build: app' "$entry"; then parts+=("${apps[@]}"); fi
  {
    printf '#!/usr/bin/env bash\n'
    printf '# Generated by build.sh from %s - do not edit, edit src/ and rebuild.\n' "$rev"
    printf 'GM_BUILD=%q\n' "$rev"
    for f in "${parts[@]}"; do
      printf '\n# ==== %s ====\n' "$f"
      cat "$f"
    done
    if [[ -n $entry ]]; then
      printf '\n# ==== %s ====\n' "$entry"
      sed '1{/^#!/d}' "$entry"
    fi
  } >"$out"
  bash -n "$out"
  chmod 755 "$out"
  printf 'built %-22s %6d lines\n' "$out" "$(wc -l <"$out")"
}

check() {
  local f rc=0
  for f in "${libs[@]}" "${apps[@]}" src/entry/*.sh build.sh; do bash -n "$f" || rc=1; done
  if command -v shellcheck >/dev/null 2>&1; then
    shellcheck -x -s bash "${libs[@]}" "${apps[@]}" src/entry/*.sh build.sh || rc=1
  else
    echo "(shellcheck not installed: only 'bash -n' was run)"
  fi
  return "$rc"
}

mkdir -p dist
case ${1:-all} in
  --check) check; exit $? ;;
  all)
    bundle dist/gm-lib.sh
    for e in src/entry/*.sh; do bundle "dist/$(basename "$e")" "$e"; done
    install -m 755 dist/gemini-menu.sh gemini-menu.sh
    ;;
  *)
    [[ -f src/entry/$1.sh ]] || { echo "no such entry: src/entry/$1.sh" >&2; exit 2; }
    bundle "dist/$1.sh" "src/entry/$1.sh"
    if [[ $1 == gemini-menu ]]; then install -m 755 dist/gemini-menu.sh gemini-menu.sh; fi
    ;;
esac
