# shellcheck shell=bash
# 12-install.sh - put the tool on the PATH: /usr/local/bin/gemini-menu (the file) and /usr/local/bin/gemini
# (a symlink to it), so a person types just  gemini.
#
#   curl -fsSL URL | sudo bash -s -- install      one line, nothing to chmod, nothing to name
#   ./gemini-menu.sh                              the first interactive run installs it too (as root)
#   gemini-menu iran|foreign setup                setup installs it as well (the Iran health timer runs that copy)
#
# Safety: a 'gemini' that is NOT this tool is never overwritten (Google ships a Gemini CLI with the same name).
# If one exists, the link is skipped with an explanation; gemini-menu always works. GM_FORCE_LINK=1 overrides.

LINK_PATH=$GM_ROOT/usr/local/bin/gemini
GM_INSTALL_URL=${GM_INSTALL_URL:-https://raw.githubusercontent.com/mahdizo3181/shecan-manager/main/gemini-menu.sh}
GM_LINK_OK=0

gm_is_root() { [[ $EUID -eq 0 || ${GM_ASSUME_ROOT:-0} == 1 ]]; }
gm_is_ours() { [[ -f $1 ]] && grep -qs 'Generated by build.sh' "$1"; }

# gm_self_source -> prints the path of a readable copy of this tool (this very file, or a fresh download
# when the script was piped into bash and so does not exist on disk).
gm_self_source() {
  local dl
  if [[ -n $GM_SELF && -r $GM_SELF ]]; then
    printf '%s' "$GM_SELF"
    return 0
  fi
  command -v curl >/dev/null 2>&1 || { ui_err "curl is needed to fetch the tool (it was piped into bash, so there is no file to copy)" >&2; return 1; }
  gm_tmp_init
  dl=$GM_TMP/gemini-menu.download
  ui_note "this script was piped into bash: downloading a copy from $GM_INSTALL_URL" >&2
  curl -fsSL --max-time 60 -o "$dl" "$GM_INSTALL_URL" || { ui_err "could not download $GM_INSTALL_URL" >&2; return 1; }
  if [[ ! -s $dl ]] || ! head -n 1 "$dl" 2>/dev/null | grep -q '^#!.*bash' || ! bash -n "$dl" 2>/dev/null || ! gm_is_ours "$dl"; then
    ui_err "the downloaded file is not a valid gemini-menu script - nothing was installed" >&2
    return 1
  fi
  printf '%s' "$dl"
}

# gm_ensure_link: /usr/local/bin/gemini -> gemini-menu. Never clobbers somebody else's 'gemini'. Always returns 0.
gm_ensure_link() {
  local want have other
  GM_LINK_OK=0
  want=$(readlink -f "$INSTALL_PATH" 2>/dev/null || echo "$INSTALL_PATH")
  if [[ -L $LINK_PATH ]]; then
    have=$(readlink -f "$LINK_PATH" 2>/dev/null || true)
    if [[ $have == "$want" ]]; then
      GM_LINK_OK=1
      ui_ok "the command 'gemini' is ready ($LINK_PATH)"
      return 0
    fi
    if gm_is_ours "$have"; then
      rm -f "$LINK_PATH"                       # a stale link to an older copy of this tool
    else
      ui_warn "$LINK_PATH is a link to something else ($have): left alone. Use: gemini-menu"
      return 0
    fi
  elif [[ -e $LINK_PATH ]]; then
    if gm_is_ours "$LINK_PATH"; then
      rm -f "$LINK_PATH"                       # an old plain copy of this tool: replace it with the link
    else
      ui_warn "$LINK_PATH exists and is not this tool (Google's Gemini CLI?): left alone. Use: gemini-menu"
      return 0
    fi
  fi
  other=$(command -v gemini 2>/dev/null || true)
  if [[ -n $other && $other != "$LINK_PATH" && ${GM_FORCE_LINK:-0} != 1 ]]; then
    ui_warn "another 'gemini' is already on the PATH ($other): not shadowing it. Use: gemini-menu  (or GM_FORCE_LINK=1 gemini-menu install)"
    return 0
  fi
  mkdir -p "$(dirname "$LINK_PATH")"
  ln -s "$(basename "$INSTALL_PATH")" "$LINK_PATH"
  GM_LINK_OK=1
  ui_ok "created the command 'gemini' ($LINK_PATH -> $(basename "$INSTALL_PATH"))"
}

# gm_install_all: the file, then the link. Returns 1 only when the FILE could not be installed.
gm_install_all() {
  local src t
  if is_dry; then
    dry_say "would install this tool as $INSTALL_PATH and link it as $LINK_PATH (the command: gemini)"
    return 0
  fi
  src=$(gm_self_source) || return 1
  mkdir -p "$(dirname "$INSTALL_PATH")"
  if [[ -x $INSTALL_PATH ]] && cmp -s "$src" "$INSTALL_PATH"; then
    ui_ok "$INSTALL_PATH is up to date"
  else
    t=$(mktemp -p "$(dirname "$INSTALL_PATH")" .gm.XXXXXX)
    cat "$src" >"$t"
    chmod 755 "$t"
    chown root:root "$t" 2>/dev/null || true
    mv -f "$t" "$INSTALL_PATH"                 # atomic: a running timer never sees half a file
    ui_ok "installed $INSTALL_PATH"
  fi
  gm_ensure_link
  return 0
}

# The action behind `gemini-menu install`, the menu item and the piped one-liner.
gm_act_install() {
  iran_require_root
  act_step "Install the tool and the 'gemini' command"
  gm_install_all || act_fail "the tool could not be installed as $INSTALL_PATH"
  if iran_installed && ! is_dry; then
    # the health timer must run the freshly installed copy
    iran_load_runtime
    iran_write_timer_units
    must systemctl daemon-reload
    ui_ok "the health timer runs $INSTALL_PATH"
  fi
  if ((GM_LINK_OK)); then ui_say "Done. From now on just type:  ${C_B}gemini${C_0}"; fi
}
